server:
  port: 8090

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true
  data:
    redis:
      host: localhost # later => redis.prod.internal
      port: 6379
      timeout: 2000 # Fails fast
      lettuce: # redis client for the spring boot, non-blocking, scalable
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1

logging:
  level:
    root: INFO
    com.ykw: DEBUG
    # enable security debugging (IMPORTANT)
    org.springframework.security: DEBUG
    org.springframework: WARN
    org.springframework.web: DEBUG

jwt:
  private-key: classpath:keys/private.pem
  public-key: classpath:keys/public.pem
  expiration: 15m

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always