server:
  port: 8094

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/article_likes_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
  jpa:
    hibernate:
      ddl-auto: validate ## validate the scehma and make no changes to the database
    database: postgresql
    show-sql: true

logging:
  level:
    org.flywaydb.core: debug

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always