server:
  port: 8081  # Gateway runs on 8081 (entry point for all client requests)

spring:
  application:
    name: api-gateway

  config:
    import:
      - classpath:config/routes.yml
      - classpath:config/security.yml
      - classpath:config/resilience.yml
      - classpath:config/logging.yml
      - classpath:config/management.yml