spring:
  application:
    name: api-gateway

  profiles:
    active: dev   # default

  config:
    import:
      - classpath:config/base/routes.yml
      - classpath:config/base/resilience.yml
      - classpath:config/base/security.yml
      - classpath:config/base/logging.yml
      - classpath:config/base/management.yml
      - classpath:config/${spring.profiles.active}/infrastructure.yml

server:
  port: ${SERVER_PORT:8081}