server:
  port: 8081

gateway:
  health:
    interval: 5000
    services:
      auth-service: http://localhost:8090
      profile-service: http://localhost:8091
      article-service: http://localhost:8092
      likes-service: http://localhost:8093
      comments-service: http://localhost:8094
      follows-service: http://localhost:8095

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.cloud.gateway: WARN
    reactor.netty: WARN
    io.netty: WARN
    com.ykw: INFO

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # AUTH SERVICE API
        - id: auth-service-api
          uri: http://localhost:8090
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # AUTH SERVICE INTERNAL
        - id: auth-service-internal
          uri: http://localhost:8090
          predicates:
            - Path=/internal/auth/**
          filters:
            - StripPrefix=2

        # PROFILE SERVICE API
        - id: profile-service-api
          uri: http://localhost:8091
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

        # PROFILE SERVICE INTERNAL
        - id: profile-service-internal
          uri: http://localhost:8091
          predicates:
            - Path=/internal/users/**
          filters:
            - StripPrefix=2

        # ARTICLE SERVICE
        - id: article-service
          uri: http://localhost:8092
          predicates:
            - Path=/articles/**

        # ARTICLE LIKES SERVICE
        - id: article-likes-service
          uri: http://localhost:8093
          predicates:
            - Path=/likes/**

        # ARTICLE COMMENTS SERVICE
        - id: article-comments-service
          uri: http://localhost:8094
          predicates:
            - Path=/comments/**

        # FOLLOWS SERVICE
        - id: follows-service
          uri: http://localhost:8095
          predicates:
            - Path=/follows/**
