server:
  port: 8095

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/article_comments_db
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    org.flywaydb.core: debug