syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.ykw.proto";
option java_outer_classname = "ArticleCacheProto";

service ArticleCacheService {

  rpc GetArticleBySlug (GetArticleRequest) returns (GetArticleResponse);

}

message GetArticleRequest {
  string slug = 1;
}

message GetArticleResponse {
  bool found = 1;
  Article article = 2;
}

message Article {
  string id = 1;
  string slug = 2;
  string title = 3;
  string subtitle = 4;
  string content = 5;
  string status = 6;
  string coverImageUrl = 7;
  string publishedAt = 8;
  string createdAt = 9;
  string updatedAt = 10;
  Author author = 11;
}

message Author {
  int64 id = 1;
  string name = 2;
  string profileImageUrl = 3;
}