spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000   # fail fast if service is unreachable (2s)
        response-timeout: 5s    # don't wait forever for slow responses
      routes:
        - id: auth-service-api
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/auth/**
          filters:
            - name: Retry
              args:
                retries: 2
                methods: GET
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
                exceptions:
                  - java.io.IOException
                  - java.net.ConnectException
                backoff:
                  firstBackoff: 100ms # retry1 - wait 100ms, retry 2 - wait 200ms, retry 3 -> wait 400ms
                  maxBackoff: 1s
                  factor: 2
                  basedOnPreviousValue: true
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth

        - id: auth-service-internal
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/internal/auth/**
          filters:
            - StripPrefix=2  # remove /internal/auth before forwarding

        - id: profile-service-api
          uri: ${PROFILE_SERVICE_URL}
          predicates:
            - Path=/api/users/**
          filters:
            # Retry comes FIRST
            - name: Retry
              args:
                retries: 2
                methods: GET,PUT   # only safe (idempotent) methods
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
                backoff:
                  firstBackoff: 100ms # retry1 - wait 100ms, retry 2 - wait 200ms, retry 3 -> wait 400ms
                  maxBackoff: 1s
                  factor: 2
                  basedOnPreviousValue: true
            # Circuit breaker to prevent cascading failures if profile-service is slow/down
            - name: CircuitBreaker
              args:
                name: profileServiceCircuitBreaker
                fallbackUri: forward:/fallback/profile  # fallback handled inside gateway

        - id: profile-service-internal
          uri: ${PROFILE_SERVICE_URL}
          predicates:
            - Path=/internal/users/**
          filters:
            - StripPrefix=2

        - id: article-service
          uri: ${ARTICLE_SERVICE_URL}
          predicates:
            - Path=/api/articles/**
          filters:
            - name: Retry
              args:
                retries: 2
                methods: GET
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
            - name: CircuitBreaker
              args:
                name: articleServiceCircuitBreaker
                fallbackUri: forward:/fallback/articles

        # ---------------- LIKES SERVICE ----------------
        - id: article-likes-service
          uri: ${LIKES_SERVICE_URL}
          predicates:
            - Path=/api/likes/**
          filters:
            - name: Retry
              args:
                retries: 2
                methods: GET
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
            - name: CircuitBreaker
              args:
                name: likesServiceCircuitBreaker
                fallbackUri: forward:/fallback/likes

        - id: article-comments-service
          uri: ${COMMENTS_SERVICE_URL}
          predicates:
            - Path=/api/comments/**
          filters:
            - name: Retry
              args:
                retries: 2
                methods: GET
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
            - name: CircuitBreaker
              args:
                name: commentsServiceCircuitBreaker
                fallbackUri: forward:/fallback/comments

        - id: follows-service
          uri: ${FOLLOWS_SERVICE_URL}
          predicates:
            - Path=/api/follows/**
          filters:
            - name: Retry
              args:
                retries: 2
                methods: GET
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
            - name: CircuitBreaker
              args:
                name: followsServiceCircuitBreaker
                fallbackUri: forward:/fallback/follows