spring:
  application:
    name: article-follows-service

  profiles:
    active: dev

  config:
    import:
      - classpath:config/base/data.yml
      - classpath:config/base/security.yml
      - classpath:config/base/logging.yml
      - classpath:config/base/management.yml

      - classpath:config/${spring.profiles.active}/infrastructure.yml

server:
  port: ${SERVER_PORT:8095}