spring:
  data:
    redis:
      host: localhost
      port: 6379

gateway:
  health:
    interval: 5000
    services:
      auth-service: http://localhost:8090
      profile-service: http://localhost:8091
      article-service: http://localhost:8092
      article-likes-service: http://localhost:8093
      article-comments-service: http://localhost:8094
      article-follows-service: http://localhost:8095

AUTH_SERVICE_URL: http://localhost:8090
PROFILE_SERVICE_URL: http://localhost:8091
ARTICLE_SERVICE_URL: http://localhost:8092
LIKES_SERVICE_URL: http://localhost:8093
COMMENTS_SERVICE_URL: http://localhost:8094
FOLLOWS_SERVICE_URL: http://localhost:8095