spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

gateway:
  health:
    interval: 5000

AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
PROFILE_SERVICE_URL: ${PROFILE_SERVICE_URL}
ARTICLE_SERVICE_URL: ${ARTICLE_SERVICE_URL}
LIKES_SERVICE_URL: ${LIKES_SERVICE_URL}
COMMENTS_SERVICE_URL: ${COMMENTS_SERVICE_URL}
FOLLOWS_SERVICE_URL: ${FOLLOWS_SERVICE_URL}